In [1]:
import numpy as np

In [12]:
x = np.array([1,2,3])

In [29]:
y = x.reshape(x.shape[0],-1)

In [33]:
a = [[1,2,3],[4,5,6]]
b = [[1,2],[4,5],[3,6]]
c = np.outer(a,b)
d =np.outer(b,a)
c

array([[ 1,  2,  4,  5,  3,  6],
       [ 2,  4,  8, 10,  6, 12],
       [ 3,  6, 12, 15,  9, 18],
       [ 4,  8, 16, 20, 12, 24],
       [ 5, 10, 20, 25, 15, 30],
       [ 6, 12, 24, 30, 18, 36]])

In [34]:
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 3,  6,  9, 12, 15, 18],
       [ 6, 12, 18, 24, 30, 36]])

In [5]:
class ValueNode(object):
    """Computation graph node having no input but simply holding a value"""
    def __init__(self, node_name):
        self.node_name = node_name
        self.out = None
        self.d_out = None

    def forward(self):
        self.d_out = np.zeros(self.out.shape)
        return self.out

    def backward(self):
        return self.d_out

    def get_predecessors(self):
        return []
    

In [8]:
x = ValueNode("x")
x.out = np.array([1,2,3])

In [11]:
x.forward()

array([1, 2, 3])